### ISSUE TITLE
Error running bot

### ISSUE THREAD

**Issue by ghost** [gumblex/tg-irc-relay#2]
Getting the following error, can you help?

Omnimushu@masteruk:~/tg-irc-relay$ python3 relay.py
Traceback (most recent call last):
  File "relay.py", line 47, in <module>
    USERAGENT = 'TgIRCRelay/%s %s' % (**version**, HSession.headers["User-Agent"           ])
KeyError: 'User-Agent'

**Comment by ghost** [comment]
Thanks for the quick reply. Ok I made this change now I get:

Omnimushu@masteruk:~/tg-irc-relay$ python3 relay.py
Traceback (most recent call last):
File "relay.py", line 541, in
CFG = json.load(open('config.json', 'r', encoding='utf-8'))
File "/usr/lib/python3.2/json/init.py", line 264, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "/usr/lib/python3.2/json/init.py", line 309, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.2/json/decoder.py", line 353, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.2/json/decoder.py", line 369, in raw_decode
obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 11 column 15 (char 239)

**Comment by gumblex** [comment]
Your config file seems invalid json.
Also, this script may not play well with Python 3.2. Please try a newer version.

**Comment by ghost** [comment]
Thanks again for the reply. Adjusted the config.json but now i get the following: 

Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(_self._args, *_self._kwargs)
  File "relay.py", line 127, in getircupd
    line = ircconn.parse(block=False)
  File "/home/Omnimushu/tg-irc-relay/libirc.py", line 356, in parse
    line = self.recvline(block)
  File "/home/Omnimushu/tg-irc-relay/libirc.py", line 341, in recvline
    while self.recvbuf.find(b'\n') == -1 and self.recv(block):
  File "/home/Omnimushu/tg-irc-relay/libirc.py", line 301, in recv
    except ssl.SSLWantReadError:
AttributeError: 'module' object has no attribute 'SSLWantReadError'

This is the current error i'm getting. I'm updating python now to see if that fixes it. You can contact me direct if its easier via marcbusby85@gmail.com

**Comment by gumblex** [comment]
You must use a newer version of Python, at least 3.3+ l guess.

**Comment by ghost** [comment]
I upgraded to python 3.4 and now i get this: 

Omnimushu@masteruk:~/tg-irc-relay$ python3 relay.py

# 2016-10-17 18:34:19,778 [INFO] Starting new HTTPS connection (1): api.telegram.org

# 2016-10-17 18:34:19,917 [INFO] IRC (re)connected.

# 2016-10-17 18:34:19,918 [INFO] Satellite launched.

^C# 2016-10-17 18:34:27,290 [INFO] Shut down cleanly.
Traceback (most recent call last):
  File "relay.py", line 569, in <module>
    processmsg()
  File "relay.py", line 369, in processmsg
    d = MSG_Q.get()
  File "/home/Omnimushu/python/lib/python3.4/queue.py", line 167, in get
    self.not_empty.wait()
  File "/home/Omnimushu/python/lib/python3.4/threading.py", line 290, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by marcbusby** [comment]
3.2*

**Comment by gumblex** [comment]
That's normal output.

**Comment by ghost** [comment]
hmmm ok... it doesnt join my irc channel or the server it seems. How do you run it and close the ssh session? nohup?
